### PR TITLE
Fix checkbox and radio button contrast for dark mode

### LINKED ISSUE #320: Checkbox component doesn't show "checked" state
Hi,
I noticed that, even on the rubyui.com website, the Checkbox control is not showing a "checked" state. If one clicks it, it stays the same. Something's off with the styles. If one manually removes the `appearance: none` style in the console, they start working again.

### PR DESCRIPTION
**Pull request by djalmaaraujo**
Fixes #320 

This is a continuation of #323 from @ianmurrays.

This Pull request fixes both the checkbox and the radio button styles when in a dark mode. 

Nov-19-2025 12-57-56

**Important note:** Shadcn changes the DOM implementation of the checkbox using a button and another element for the indicator. In our case, we rely on the checkbox with a `background-image` default from tailwind. This limits us to use `background-color` and `color` together like shadcn does.

### CODE REVIEW

File: lib/ruby_ui/checkbox/checkbox.rb [hunk 1]
```diff
@@ -17,9 +17,9 @@ def default_attrs
           action: "change->ruby-ui--checkbox-group#onChange change->ruby-ui--form-field#onInput invalid->ruby-ui--form-field#onInvalid"
         },
         class: [
-          "peer h-4 w-4 shrink-0 rounded-sm border border-primary ring-offset-background accent-primary",
+          "peer h-4 w-4 shrink-0 rounded-sm border-input ring-offset-background accent-primary",
```
Comment (djalmaaraujo) [inline lib/ruby_ui/checkbox/checkbox.rb]: This is the default.
